server:
  port: 8085  # Topics Service port

spring:
  kafka:
    bootstrap-servers: localhost:9092  # Kafka broker URL
    admin:
      client-id: kafka-topics-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true